# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignatura', '0001_initial'),
        ('Tutor', '0002_tutor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='asignaturas',
            field=models.ManyToManyField(to='Asignatura.Asignatura'),
        ),
    ]
