# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0003_tutor_asignaturas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
