# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0004_auto_20180909_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='imagen',
        ),
    ]
