# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombreAsig', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
