# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('idAsignatura', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombreAsig', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('idTutor', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='photos')),
                ('asignaturas', models.ManyToManyField(to='app.Asignatura')),
            ],
        ),
    ]
